﻿/************************************************************
 Payu Asp.Net Entegrasyon için Sınıf Kütüphanesi dosyası
 Yazan Vefa Kayacı <vefakayaci@gmail.com>
 http://www.gurafe.com
 Kullanımında ve dağıtımında herhangi bir kısıt yoktur
 ************************************************************/

namespace PayuLib
{
    public static class Constants 
    {
        /// <summary>
        /// Generated by PayuLib
        /// </summary>
       public static string ReqId = "ReqId";
        
        /// <summary>
       /// Customer remote ip address
        /// </summary>
        public static string CustomerIp = "CustomerIp";

        /// <summary>
        /// Own extra Order Ident
        /// </summary>
        public static string ExtOrderId = "ExtOrderId";

        /// <summary>
        /// Own Merchant Pos Ident
        /// </summary>
        public static string MerchantPosId = "MerchantPosId";

        /// <summary>
        /// Description for this payment
        /// </summary>
        public static string Description = "Description";

        /// <summary>
        /// Currency Code (Default: "TRY")
        /// </summary>
        public static string CurrencyCode = "CurrencyCode";

        /// <summary>
        /// Total Amount for Payment
        /// </summary>
        public static string TotalAmount = "TotalAmount";

        /// <summary>
        /// Payment Method default: "DEFAULT"
        /// </summary>
        public static string PayMethod = "PayMethod";

        /// <summary>
        /// Buyer First Name
        /// </summary>
        public static string FirstName = "FirstName";

        /// <summary>
        /// Buyer Last Name
        /// </summary>
        public static string LastName = "LastName";

        /// <summary>
        /// Country Code For Buyer Example: "en"
        /// </summary>
        public static string CountryCode = "CountryCode";

        /// <summary>
        /// Buyer Email Address
        /// </summary>
        public static string Email = "Email";

        /// <summary>
        /// Buyer Phone Number
        /// </summary>
        public static string PhoneNumber = "PhoneNumber";

        /// <summary>
        /// Buyer Language
        /// </summary>
        public static string Language = "Language";

        /// <summary>
        /// Product Name
        /// </summary>
        public static string Name = "Name";

        /// <summary>
        /// Unit Price for current product
        /// </summary>
        public static string UnitPrice = "UnitPrice";

        /// <summary>
        /// Quantity for current product
        /// </summary>
        public static string Quantity = "Quantity";
    }
}